service: apollo-lambda
provider:
  name: aws
  runtime: nodejs10.x
functions:
  graphql:
    handler: dist/index.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
