service: public-badges

custom:
  registry_bucket: public-badges-registry-${opt:stage}

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.registry_bucket}/*"
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: "*"

functions:
  graphql:
    handler: dist/index.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: playground
          method: any
          cors: true
  registerOrganization:
    handler: dist/index.registerOrganization
    environment:
      REGISTRY_BUCKET: ${self:custom.registry_bucket}
    events:
      - eventBridge:
          pattern:
            source:
              - public-badges.api-handler
            detail-type: ["ORGANIZATION_REGISTRATION_REQUESTED"]
  echo:
    handler: dist/index.echo
    events:
      - eventBridge:
          pattern:
            source:
              - public-badges.register-organization-handler
            detail-type: ["ORGANIZATION_APPROVAL_REQUESTED"]
  indexer:
    handler: dist/index.approve
    events:
      - s3: ${self:custom.registry_bucket}
