export {
  Resolvers,
  MutationResolvers,
  QueryResolvers,
  OpenBadgeResolvers,
  OpenBadgeClassResolvers,
  OpenBadgeArtifactResolvers,
  OpenBadgeCriteriaResolvers,
  OpenBadgeRecipientResolvers,
  OpenBadgeProofResolvers,
  ContactResolvers,
  OrganizationResolvers,
  PendingOrganizationResolvers,
  ScenarioResolvers,
  ValueCaseResolvers,
  ProofResolvers,
  PublicBadgeResolvers,
  PendingPublicBadgeResolvers,
  ApprovedPublicBadgeResolvers,
  RejectedPublicBadgeResolvers,
  SignedPublicBadgeResolvers,
  ApprovedOrganizationResolvers
} from "./generated/graphql";
