export enum PublicBadgesEventType {
  ORGANIZATION_REGISTRATION_REQUESTED = "ORGANIZATION_REGISTRATION_REQUESTED",
  ORGANIZATION_APPROVAL_REQUESTED = "ORGANIZATION_APPROVAL_REQUESTED",
  ORGANIZATION_APPROVAL_ACCEPTED = "ORGANIZATION_APPROVAL_ACCEPTED",
  ORGANIZATION_APPROVED = "ORGANIZATION_APPROVED",
  NEW_BADGECLASS_PROPOSED = "NEW_BADGECLASS_PROPOSED",
  BADGE_ISSUANCE_REQUESTED = "BADGE_ISSUANCE_REQUESTED",
  BADGE_ISSUANCE_APPROVED = "BADGE_ISSUANCE_APPROVED",
  BADGE_ISSUANCE_REJECTED = "BADGE_ISSUANCE_REJECTED",
  BADGE_INSTANCE_UPDATED = "BADGE_INSTANCE_UPDATED",
  OPEN_BADGES_ARTIFACT_CREATED = "OPEN_BADGES_ARTIFACT_CREATED",
  OPEN_BADGES_ARTIFACT_SIGNED = "OPEN_BADGES_ARTIFACT_SIGNED",
  BADGE_INSTANCE_SIGNED = "BADGE_INSTANCE_SIGNED"
}
